name       : crow-translate
version    : 2.3.1
release    : 1
source     :
    - https://github.com/crow-translate/crow-translate/archive/2.3.1.tar.gz : b82919cb34bb66fcd7b4eb88de4025bcb0cd569cce6bb548657cb07c7bdcbdd2
    - https://github.com/crow-translate/QOnlineTranslator/archive/1.2.2.tar.gz : 40df3af650048b651e4c624cf33f662deb392880107ad4e8cc4f4684e78042d5
    - https://github.com/itay-grudev/SingleApplication/archive/v3.0.19.tar.gz : 9405fd259288b2a862e91e5135bccee936f0438e1b32c13603277132309d15e0
    - https://github.com/Skycoder42/QHotkey/archive/1.3.0.tar.gz : d21867b4f15a67c03d26c960da864a63368ccdf7da2dfaa545c135aad506085e
    - https://github.com/Skycoder42/QTaskbarControl/archive/2.0.0.tar.gz : 85039ca8ff899ed724ed16b719be7a814392a67ad53b4b59f160f73fb53dc74c
    - https://github.com/crow-translate/QGitTag/archive/1.0.3.tar.gz : 79d9add6bd04c77bf8fc7a7bc83435fd01e9825352d8318923816cc03a7cf4ed
homepage   : https://crow-translate.github.io/
license    : 
    - BSD-3-Clause
    - GPL-3.0-or-later
    - MIT
component  : office
summary    : A simple translator that allows to translate and speak text using Google, Yandex and Bing.
description: |
    Crow Translate is a simple and lightweight translator programmed in C++ / Qt that allows to translate and speak text using Google, Yandex and Bing translate API.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - gstreamer-1.0-plugins-good
setup      : |
    # Include submodules into the project
    for submodules in 1.0.3 1.2.2 1.3.0 2.0.0 v3.0.19; do
    tar xvf $sources/${submodules}.tar.gz; done
    mv QGitTag-1.0.3/*  src/qgittag
    mv QOnlineTranslator-1.2.2/* src/qonlinetranslator
    mv QHotkey-1.3.0/* src/third-party/qhotkey
    mv QTaskbarControl-2.0.0/* src/third-party/qtaskbarcontrol
    mv SingleApplication-3.0.19/* src/third-party/singleapplication
build      : |
    qmake
install    : |
    %make_install INSTALL_ROOT=$installdir
