name       : crow-translate
version    : 2.4.1
release    : 3
source     :
    - https://github.com/crow-translate/crow-translate/archive/2.4.1.tar.gz : dc2f61eccd42741e68a342578edf62c91430decec5d1ef168426b67e052fcf90
    - https://github.com/crow-translate/QOnlineTranslator/archive/1.2.4.tar.gz : 2d1839aecc0e5a540941aa65653a4d5edad24f73771cef8dd564304b131671bf
    - https://github.com/itay-grudev/SingleApplication/archive/v3.1.3.1.tar.gz : bbc20faa3e914cda8fe94b5d0bf98af640d3298a791a16cad4571a9ccbf1d030
    - https://github.com/Skycoder42/QHotkey/archive/1.4.0.tar.gz : 5694f0b35b8051a1d68a2172081f0698bf72aba7f350740d2c6a3fe7de4b0ae3
    - https://github.com/Skycoder42/QTaskbarControl/archive/2.0.1.tar.gz : b2f956bdc5fdba1477ca7f4bde9759a120055407e4a7cc0c9efbc3934ae72b01
homepage   : https://crow-translate.github.io/
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - MIT
component  : office
summary    : A simple translator that allows to translate and speak text using Google, Yandex and Bing.
description: |
    Crow Translate is a simple and lightweight translator programmed in C++ / Qt that allows to translate and speak text using Google, Yandex and Bing translate API.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
rundeps    :
    - gstreamer-1.0-plugins-good
setup      : |
    # Include submodules into the project
    for submodules in 1.2.4 1.4.0 2.0.1 v3.1.3.1; do
    tar xvf $sources/${submodules}.tar.gz; done
    mv QHotkey-1.4.0/* src/third-party/qhotkey
    mv QOnlineTranslator-1.2.4/* src/qonlinetranslator
    mv QTaskbarControl-2.0.1/* src/third-party/qtaskbarcontrol
    mv SingleApplication-3.1.3.1/* src/third-party/singleapplication
    
    %cmake
build      : |
    %make
install    : |
    %make_install
