name       : crow-translate
version    : 2.5.0
release    : 4
source     :
    - https://github.com/crow-translate/crow-translate/archive/2.5.0.tar.gz : 80d0dcf2029fac36e8117b9af404c43dc34531993d1c2c4f9e2f1262572e4f02
    - https://github.com/crow-translate/QOnlineTranslator/archive/1.3.0.tar.gz : d45ea62fedaf817aafa1f2bc3781d20192bfbaf9e30558f6591ed5575c2001a8
    - https://github.com/itay-grudev/SingleApplication/archive/v3.1.4.tar.gz : e3b75de67999d340e17f224286622ed8ffc3ed023bc573e369309181c1a365a9
    - https://github.com/Skycoder42/QHotkey/archive/1.4.1.tar.gz : 516726432ba21aeab11c37d979d80a300108b774ee43be078dddd2e6055226d8
    - https://github.com/Skycoder42/QTaskbarControl/archive/2.0.1.tar.gz : b2f956bdc5fdba1477ca7f4bde9759a120055407e4a7cc0c9efbc3934ae72b01
homepage   : https://crow-translate.github.io/
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - MIT
component  : office
summary    : A simple translator that allows to translate and speak text using Google, Yandex and Bing.
description: |
    Crow Translate is a simple and lightweight translator programmed in C++ / Qt that allows to translate and speak text using Google, Yandex and Bing translate API.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
rundeps    :
    - gstreamer-1.0-plugins-good
setup      : |
    # Include submodules into the project
    for submodules in 1.3.0 1.4.1 2.0.1 v3.1.4; do
    tar xvf $sources/${submodules}.tar.gz; done
    mv QHotkey-1.4.1/* src/third-party/qhotkey
    mv QOnlineTranslator-1.3.0/* src/qonlinetranslator
    mv QTaskbarControl-2.0.1/* src/third-party/qtaskbarcontrol
    mv SingleApplication-3.1.4/* src/third-party/singleapplication

    %cmake
build      : |
    %make
install    : |
    %make_install
