name       : crow-translate
version    : 2.3.2
release    : 2
source     :
    - https://github.com/crow-translate/crow-translate/archive/2.3.2.tar.gz : 4dbaffbc9c9e78e0920695ff21115cf99c5bc7b1afa693bb6b7d364dcc856610
    - https://github.com/crow-translate/QGitTag/archive/1.0.4.tar.gz : bd6717e1245facd0558633810f99ef1583e8e65692db55e516050ba09dfef2be
    - https://github.com/crow-translate/QOnlineTranslator/archive/1.2.3.tar.gz : 20cc2736f6dec3a376b6746525076de2760e997085fb3d3f2776f0ce5b676182
    - https://github.com/itay-grudev/SingleApplication/archive/v3.1.3.tar.gz : 4585f02fbfba61626e4ed4f1815b847c72f1593bffac6015f6e75f514094f148
    - https://github.com/Skycoder42/QHotkey/archive/1.3.0.tar.gz : d21867b4f15a67c03d26c960da864a63368ccdf7da2dfaa545c135aad506085e
    - https://github.com/Skycoder42/QTaskbarControl/archive/2.0.0.tar.gz : 85039ca8ff899ed724ed16b719be7a814392a67ad53b4b59f160f73fb53dc74c
homepage   : https://crow-translate.github.io/
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - MIT
component  : office
summary    : A simple translator that allows to translate and speak text using Google, Yandex and Bing.
description: |
    Crow Translate is a simple and lightweight translator programmed in C++ / Qt that allows to translate and speak text using Google, Yandex and Bing translate API.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - gstreamer-1.0-plugins-good
setup      : |
    # Include submodules into the project
    for submodules in 1.0.4 1.2.3 1.3.0 2.0.0 v3.1.3; do
    tar xvf $sources/${submodules}.tar.gz; done
    mv QGitTag-1.0.4/*  src/qgittag
    mv QHotkey-1.3.0/* src/third-party/qhotkey
    mv QOnlineTranslator-1.2.3/* src/qonlinetranslator
    mv QTaskbarControl-2.0.0/* src/third-party/qtaskbarcontrol
    mv SingleApplication-3.1.3/* src/third-party/singleapplication
build      : |
    qmake
install    : |
    %make_install INSTALL_ROOT=$installdir
