name       : crow-translate
version    : 2.9.4
release    : 20
source     :
    - https://github.com/crow-translate/crow-translate/releases/download/2.9.4/crow-translate-2.9.4-source.tar.gz : f142fbe5d605dd3ea25778088e3fda50477f05a0acf38f25e9de264c39699f93
homepage   : https://crow-translate.github.io/
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - MIT
component  : office
summary    : A simple translator that allows to translate and speak text using Google, Yandex and Bing
description: |
    Crow Translate is a simple and lightweight translator programmed in C++ / Qt that allows to translate and speak text using Google, Yandex and Bing translate API.
networking : yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(tesseract)
    - pkgconfig(x11)
    - extra-cmake-modules
    - git
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
