name       : crow-translate
version    : 2.7.0
release    : 10
source     :
    - https://github.com/crow-translate/crow-translate/archive/2.7.0.tar.gz : 53a1af7f1a239cf1125bc3acc031579d80787802585301a43c93fbd45b8d348f
homepage   : https://crow-translate.github.io/
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - MIT
component  : office
summary    : A simple translator that allows to translate and speak text using Google, Yandex and Bing
description: |
    Crow Translate is a simple and lightweight translator programmed in C++ / Qt that allows to translate and speak text using Google, Yandex and Bing translate API.
networking : yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(tesseract)
    - pkgconfig(x11)
    - extra-cmake-modules
    - git
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
